kind: pipeline
type: docker
name: default
steps:
- name: builing_wiseapi
  image: java:openjdk-8-alpine
  commands:
    - ls
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    username: varkalaramalingam
  when:
    status: [ success, failure ]
    event: push
