kind: pipeline
type: docker
name: default
steps:
- name: builing_wiseapi
  image: java:openjdk-8-alpine
  commands:
    - ./gradlew clean build
# to push docker image into dockerhub
- name: publish
  image: plugins/docker
  environment:
    repo: ramalingam81/dronewiseapi
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
