kind: pipeline
name: default
type: docker
steps:
- name: test
  image: node
  commands:
  - ls
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    username: varkalaramalingam
    template: >
      {{#success build.status}}
        build {{build.number}} success_lingam. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    status: [ success, failure ]
    
