kind: pipeline
name: default
type: docker
steps:
- name: test
  image: node
  commands:
  - ls
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    status: [ success, failure ]
    
